UAT_ITEM_MAPPING = {
  ["item/Melee"]         = { code = "espada",             kind = "toggle" },
  ["item/ChargedAttack"] = { code = "ataque_carregado",   kind = "toggle" },
  ["item/Dash"]          = { code = "investida",          kind = "toggle" },
  ["item/DoubleJump"]    = { code = "pulo_duplo",         kind = "toggle" },
  ["item/flames"]        = { code = "chamas",             kind = "toggle" },
  ["item/waterUpgrade"]  = { code = "respiracao",         kind = "toggle" },
  ["item/Ghost"]         = { code = "fantasma",           kind = "toggle" },
  ["item/DoorKey1"]      = { code = "chave1",             kind = "toggle" },
  ["item/DoorKey2"]      = { code = "chave2",             kind = "toggle" },
  ["item/DoorKey3"]      = { code = "chave3",             kind = "toggle" },
  ["item/SpiritStrength"] = { code = "espirito_forca",    kind = "toggle" },
  ["item/Spirit1"]       = { code = "espirito_1",   kind = "toggle" },
  ["item/Spirit2"]       = { code = "espirito_2",   kind = "toggle" },
  ["item/Spirit3"]       = { code = "espirito_3",   kind = "toggle" },
  ["item/Spirit4"]       = { code = "espirito_4",   kind = "toggle" },
  ["item/Spirit5"]       = { code = "espirito_5",   kind = "toggle" },
  ["item/Spirit6"]       = { code = "espirito_6",   kind = "toggle" },
  ["item/Spirit7"]       = { code = "espirito_7",   kind = "toggle" },
  ["item/Spirit8"]       = { code = "espirito_8",   kind = "toggle" },
  ["item/Spirit9"]       = { code = "espirito_9",   kind = "toggle" },
  ["item/Spirit10"]       = { code = "espirito_10",  kind = "toggle" },
  ["item/Spirit11"]       = { code = "espirito_11",  kind = "toggle" },
  ["item/Spirit12"]       = { code = "espirito_12",  kind = "toggle" },
  ["item/Spirit13"]       = { code = "espirito_13",  kind = "toggle" },
  ["item/Spirit14"]       = { code = "espirito_14",  kind = "toggle" },
  ["item/Spirit15"]       = { code = "espirito_15",  kind = "toggle" },
  ["item/Spirit16"]       = { code = "espirito_16",  kind = "toggle" },
  ["item/Spirit17"]       = { code = "espirito_17",  kind = "toggle" },
  ["item/Spirit18"]       = { code = "espirito_18",  kind = "toggle" },
  ["item/Spirit19"]       = { code = "espirito_19",  kind = "toggle" },
  ["item/Spirit20"]       = { code = "espirito_20",  kind = "toggle" },
  ["item/Spirit21"]       = { code = "espirito_21",  kind = "toggle" },
  ["item/Spirit22"]       = { code = "espirito_22",  kind = "toggle" },
  ["item/Spirit23"]       = { code = "espirito_23",  kind = "toggle" },
  ["item/Spirit24"]       = { code = "espirito_24",  kind = "toggle" },
  ["item/Spirit25"]       = { code = "espirito_25",  kind = "toggle" },
  ["item/Spirit26"]       = { code = "espirito_26",  kind = "toggle" },
  ["item/Spirit27"]       = { code = "espirito_27",  kind = "toggle" },
  ["item/Spirit28"]       = { code = "espirito_28",  kind = "toggle" },
  ["item/Spirit29"]       = { code = "espirito_29",  kind = "toggle" },
  ["item/Spirit30"]       = { code = "espirito_30",  kind = "toggle" },
  ["item/HeartFragment"] = { code = "fragmento_coracao",  kind = "count", max = 10 },
  ["item/Spirits"]       = { code = "espirito",           kind = "count", max = 30 },
  ["item/Diaries"]       = { code = "diario",             kind = "count", max = 16 },
}
